-- Backfill Prakrit's existing applications into the persistent application table.
-- These rows become available from Supabase instead of browser-only localStorage seeds.

with manager as (
  select id
  from public.profiles
  where lower(email) in ('prakritramachandran@gmail.com', 'prakritramachandran@gmai.com')
  order by created_at desc
  limit 1
),
seed(id, row_data) as (
  values
    (
      'AXIS-L52LZTST',
      $axis_app_json$
{
  "id": "AXIS-L52LZTST",
  "name": "Fathima Shaikh",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "fathimashaikh318@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/9/2026",
  "application": {
    "applyingAsGroup": null,
    "groupRole": null,
    "groupId": "",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-6",
    "roomChoice2": "",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "5/24/2026",
    "leaseEnd": "8/16/2026",
    "fullLegalName": "Fathima Shaikh",
    "dateOfBirth": "3/18/2005",
    "ssn": "342-04-6480",
    "driversLicense": "s200-2570-5680",
    "phone": "(312) 714-7974",
    "email": "fathimashaikh318@gmail.com",
    "currentStreet": "2021 Channing Way",
    "currentCity": "Berkeley",
    "currentState": "CA",
    "currentZip": "94704",
    "currentLandlordName": "Vindium Real Estate",
    "currentLandlordPhone": "(312) 714-7974",
    "currentMoveIn": "8/15/2024",
    "currentMoveOut": "12/15/2026",
    "currentReasonLeaving": "grad",
    "employer": "Microsoft",
    "employerAddress": "One Microsoft Way, Redmond, WA 98052-7329, USA",
    "supervisorName": "N/A don't know yet",
    "supervisorPhone": "(425) 882-8080",
    "jobTitle": "Product Manger",
    "monthlyIncome": "$8,500.00",
    "annualIncome": "$102,000.00",
    "employmentStart": "5/26/2026",
    "ref1Name": "Karolina",
    "ref1Relationship": "Coworker",
    "ref1Phone": "(224) 242-0501",
    "ref2Name": "Grace",
    "ref2Relationship": "supervisor",
    "ref2Phone": "(832) 606-8409",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "fathima shaikh",
    "dateSigned": "4/9/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-NNELGWQH',
      $axis_app_json$
{
  "id": "AXIS-NNELGWQH",
  "name": "Arnav Shanbhag",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "arnavjs78@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/8/2026",
  "application": {
    "applyingAsGroup": null,
    "groupRole": null,
    "groupId": "",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-2",
    "roomChoice2": "",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "5/23/2026",
    "leaseEnd": "8/23/2026",
    "fullLegalName": "Arnav Shanbhag",
    "dateOfBirth": "12/28/2005",
    "ssn": "356049699",
    "driversLicense": "900001044321",
    "phone": "(814) 810-7714",
    "email": "arnavjs78@gmail.com",
    "currentStreet": "519 Onondaga St",
    "currentCity": "Ann Arbor",
    "currentState": "MI",
    "currentZip": "48104",
    "currentLandlordName": "None",
    "currentLandlordPhone": "",
    "currentMoveIn": "",
    "currentMoveOut": "",
    "currentReasonLeaving": "",
    "employer": "Pacific Northwest National Laboratory",
    "employerAddress": "3335 Innovation Dr, Richland, WA 99354",
    "supervisorName": "Wilson Fearn",
    "supervisorPhone": "",
    "jobTitle": "Intern",
    "monthlyIncome": "$5,000.00",
    "annualIncome": "$25,000.00",
    "employmentStart": "5/26/2026",
    "ref1Name": "Uday Shanbhag",
    "ref1Relationship": "Father",
    "ref1Phone": "(217) 840-5126",
    "ref2Name": "Aparna Joshi",
    "ref2Relationship": "Mother",
    "ref2Phone": "(217) 840-7835",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Arnav Shanbhag",
    "dateSigned": "4/8/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-JEWOOKPA',
      $axis_app_json$
{
  "id": "AXIS-JEWOOKPA",
  "name": "Jewook Park",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "jewook.parkder@gmail.com",
  "detail": "Imported from PDF - Brooklyn application signed 3/30/2026",
  "application": {
    "applyingAsGroup": null,
    "groupRole": null,
    "groupId": "",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "",
    "roomChoice2": "",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "5/1/2026",
    "leaseEnd": "8/14/2026",
    "fullLegalName": "Jewook Park",
    "dateOfBirth": "8/13/2003",
    "ssn": "",
    "driversLicense": "M194G68N9 (Passport ID)",
    "phone": "(404) 610-9875",
    "email": "jewook.parkder@gmail.com",
    "currentStreet": "1107 Mecaslin St NW",
    "currentCity": "Atlanta",
    "currentState": "GA",
    "currentZip": "30318",
    "currentLandlordName": "Nilesh Shah",
    "currentLandlordPhone": "(404) 468-5840",
    "currentMoveIn": "8/1/2025",
    "currentMoveOut": "5/1/2026",
    "currentReasonLeaving": "Moving to another apartment",
    "employer": "Microsoft",
    "employerAddress": "3600 157th Avenue NE, Redmond, WA 98052",
    "supervisorName": "Sandeep Repaka",
    "supervisorPhone": "(425) 882-8080",
    "jobTitle": "Principal Software Engineering Manager",
    "monthlyIncome": "$8,458.00",
    "annualIncome": "",
    "employmentStart": "5/18/2026",
    "ref1Name": "David Yoo",
    "ref1Relationship": "Friend",
    "ref1Phone": "(470) 435-0570",
    "ref2Name": "Kim Seungmin Yu",
    "ref2Relationship": "Friend",
    "ref2Phone": "",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Jewook Park",
    "dateSigned": "3/30/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-DAVIDYOO',
      $axis_app_json$
{
  "id": "AXIS-DAVIDYOO",
  "name": "David Hyungchan Yoo",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "davidhyoo1@gmail.com",
  "detail": "Imported from PDF - Brooklyn application signed 3/30/2026",
  "application": {
    "applyingAsGroup": null,
    "groupRole": null,
    "groupId": "",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "",
    "roomChoice2": "",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "5/14/2026",
    "leaseEnd": "8/14/2026",
    "fullLegalName": "David Hyungchan Yoo",
    "dateOfBirth": "1/24/2001",
    "ssn": "761-19-0665",
    "driversLicense": "070117931",
    "phone": "(470) 435-0530",
    "email": "davidhyoo1@gmail.com",
    "currentStreet": "1107 Mecaslin St NW",
    "currentCity": "Atlanta",
    "currentState": "GA",
    "currentZip": "30318",
    "currentLandlordName": "Nilesh Shah",
    "currentLandlordPhone": "(404) 468-5840",
    "currentMoveIn": "8/1/2025",
    "currentMoveOut": "7/31/2026",
    "currentReasonLeaving": "Sublease for internship",
    "employer": "Microsoft",
    "employerAddress": "One Microsoft Way, Redmond, WA 98052",
    "supervisorName": "Kaitlin Krause",
    "supervisorPhone": "(425) 882-8080",
    "jobTitle": "Supply Chain Planner Intern",
    "monthlyIncome": "",
    "annualIncome": "$81,840.00",
    "employmentStart": "5/18/2026",
    "ref1Name": "Jewook Park",
    "ref1Relationship": "Friend",
    "ref1Phone": "(404) 610-9875",
    "ref2Name": "Christine Yoo",
    "ref2Relationship": "Friend",
    "ref2Phone": "(602) 620-6275",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "David Yoo",
    "dateSigned": "3/30/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-KGD8JWSJ',
      $axis_app_json$
{
  "id": "AXIS-KGD8JWSJ",
  "name": "Connor D Federico Grome",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "connorgrome89@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/15/2026",
  "application": {
    "applyingAsGroup": null,
    "groupRole": null,
    "groupId": "",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-3",
    "roomChoice2": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-5",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "6/14/2026",
    "leaseEnd": "9/5/2026",
    "fullLegalName": "Connor D Federico Grome",
    "dateOfBirth": "5/11/2005",
    "ssn": "025-88-7735",
    "driversLicense": "SA6540073",
    "phone": "(774) 270-2926",
    "email": "connorgrome89@gmail.com",
    "currentStreet": "22 Walden Drive",
    "currentCity": "Natick",
    "currentState": "MA",
    "currentZip": "1760",
    "currentLandlordName": "Jon Wangler",
    "currentLandlordPhone": "(508) 655-5500",
    "currentMoveIn": "5/11/2005",
    "currentMoveOut": "4/15/2026",
    "currentReasonLeaving": "Still live there",
    "employer": "Amazon Web Services",
    "employerAddress": "2205 7th Ave, Seattle, WA, 98121",
    "supervisorName": "Brett Laffel",
    "supervisorPhone": "(000) 000-0000",
    "jobTitle": "General Marketing Specialist Intern",
    "monthlyIncome": "$6,683.00",
    "annualIncome": "$0.00",
    "employmentStart": "6/15/2026",
    "ref1Name": "Julie Russel",
    "ref1Relationship": "Friend / Classmate",
    "ref1Phone": "(225) 773-3212",
    "ref2Name": "Ahron Springer",
    "ref2Relationship": "Friend / Classmate",
    "ref2Phone": "(718) 551-7849",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Connor D Federico-Grome",
    "dateSigned": "4/15/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-AVUA6UPM',
      $axis_app_json$
{
  "id": "AXIS-AVUA6UPM",
  "name": "Kavinu Weerawardhene",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "Kavinuj753@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/15/2026",
  "application": {
    "applyingAsGroup": "yes",
    "groupRole": "first",
    "groupId": "AXISGRP-P45NRJL764WE",
    "groupSize": "5",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-3",
    "roomChoice2": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-4",
    "roomChoice3": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-5",
    "leaseTerm": "3-Month",
    "leaseStart": "5/20/2026",
    "leaseEnd": "8/22/2026",
    "fullLegalName": "Kavinu Weerawardhene",
    "dateOfBirth": "7/15/2005",
    "ssn": "475-53-3244",
    "driversLicense": "M000041700200",
    "phone": "(952) 290-3970",
    "email": "Kavinuj753@gmail.com",
    "currentStreet": "101 North Brooks Street",
    "currentCity": "Madison",
    "currentState": "WI",
    "currentZip": "53715",
    "currentLandlordName": "Rouse Management",
    "currentLandlordPhone": "(608) 255-4744",
    "currentMoveIn": "8/15/2025",
    "currentMoveOut": "8/15/2026",
    "currentReasonLeaving": "New Living Spot for College.",
    "employer": "Morgridge Institute for Research",
    "employerAddress": "330 N Orchard St",
    "supervisorName": "Carlos Frits",
    "supervisorPhone": "(746) 492-8131",
    "jobTitle": "Student Lab Assistant",
    "monthlyIncome": "$900.00",
    "annualIncome": "$10,800.00",
    "employmentStart": "1/20/2025",
    "ref1Name": "Patrick Grunklee",
    "ref1Relationship": "Colleague",
    "ref1Phone": "(612) 479-7924",
    "ref2Name": "Devmini Jayatilaka",
    "ref2Relationship": "Colleague",
    "ref2Phone": "(612) 425-8884",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Kavinu Weerawardhene",
    "dateSigned": "4/15/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-LUEW7J5G',
      $axis_app_json$
{
  "id": "AXIS-LUEW7J5G",
  "name": "David Macaraig",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "davidjmacaraig@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/15/2026",
  "application": {
    "applyingAsGroup": "yes",
    "groupRole": "joining",
    "groupId": "AXISGRP-P45NRJL764WE",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-1",
    "roomChoice2": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-2",
    "roomChoice3": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-5",
    "leaseTerm": "3-Month",
    "leaseStart": "5/22/2026",
    "leaseEnd": "8/21/2026",
    "fullLegalName": "David Macaraig",
    "dateOfBirth": "5/30/2004",
    "ssn": "615-45-4844",
    "driversLicense": "Y7168230",
    "phone": "(925) 890-4537",
    "email": "davidjmacaraig@gmail.com",
    "currentStreet": "5061 Art Street",
    "currentCity": "San Diego",
    "currentState": "CA",
    "currentZip": "92115",
    "currentLandlordName": "",
    "currentLandlordPhone": "",
    "currentMoveIn": "8/26/2024",
    "currentMoveOut": "5/13/2026",
    "currentReasonLeaving": "Work",
    "employer": "Pfizer",
    "employerAddress": "21823 30th Dr SE Bothell WA 98021 United States",
    "supervisorName": "Bianca Ramdath",
    "supervisorPhone": "(212) 557-9545",
    "jobTitle": "CRD/ARD",
    "monthlyIncome": "$4,640.00",
    "annualIncome": "$55,680.00",
    "employmentStart": "5/26/2026",
    "ref1Name": "Kavinu Weerawaradhene",
    "ref1Relationship": "Colleague",
    "ref1Phone": "(952) 290-3970",
    "ref2Name": "Ryan Gribble",
    "ref2Relationship": "Colleague",
    "ref2Phone": "(850) 830-8483",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "David Macaraig",
    "dateSigned": "4/15/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-PLDGTIPM',
      $axis_app_json$
{
  "id": "AXIS-PLDGTIPM",
  "name": "Tatva Prasad",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "tatvapra@usc.edu",
  "detail": "Imported from spreadsheet - signed 4/15/2026",
  "application": {
    "applyingAsGroup": "yes",
    "groupRole": "joining",
    "groupId": "AXISGRP-P45NRJL764WE",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-4",
    "roomChoice2": "",
    "roomChoice3": "",
    "leaseTerm": "3-Month",
    "leaseStart": "5/22/2026",
    "leaseEnd": "8/16/2026",
    "fullLegalName": "Tatva Prasad",
    "dateOfBirth": "7/29/2006",
    "ssn": "156-72-1516",
    "driversLicense": "Y7036608",
    "phone": "(510) 399-3322",
    "email": "tatvapra@usc.edu",
    "currentStreet": "3131 S Hoover St",
    "currentCity": "Los Angeles",
    "currentState": "CA",
    "currentZip": "90089",
    "currentLandlordName": "USC",
    "currentLandlordPhone": "",
    "currentMoveIn": "8/18/2025",
    "currentMoveOut": "5/16/2026",
    "currentReasonLeaving": "End of school term",
    "employer": "Pfizer",
    "employerAddress": "2500 223rd St SE",
    "supervisorName": "Noah Theiss",
    "supervisorPhone": "(425) 527-4000",
    "jobTitle": "Research and Development",
    "monthlyIncome": "$4,480.00",
    "annualIncome": "$53,760.00",
    "employmentStart": "5/15/2026",
    "ref1Name": "Vaahin Mehta",
    "ref1Relationship": "Roommate",
    "ref1Phone": "(630) 785-0826",
    "ref2Name": "Nitin Davuluri",
    "ref2Relationship": "Roommate",
    "ref2Phone": "(904) 805-2953",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Tatva Prasad",
    "dateSigned": "4/15/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-EDEK0E02',
      $axis_app_json$
{
  "id": "AXIS-EDEK0E02",
  "name": "Ryan Gribble",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "ryan.d.gribble@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/16/2026",
  "application": {
    "applyingAsGroup": "yes",
    "groupRole": "joining",
    "groupId": "AXISGRP-P45NRJL764WE",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-4",
    "roomChoice2": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-5",
    "roomChoice3": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-8",
    "leaseTerm": "3-Month",
    "leaseStart": "5/23/2026",
    "leaseEnd": "8/21/2026",
    "fullLegalName": "Ryan Gribble",
    "dateOfBirth": "2/18/2004",
    "ssn": "765-38-5610",
    "driversLicense": "G614-724-04-058-0",
    "phone": "(850) 830-8483",
    "email": "ryan.d.gribble@gmail.com",
    "currentStreet": "4503 Sandhurst Drive",
    "currentCity": "Orlando",
    "currentState": "FL",
    "currentZip": "32817",
    "currentLandlordName": "Joey Gong",
    "currentLandlordPhone": "(407) 409-3429",
    "currentMoveIn": "7/15/2024",
    "currentMoveOut": "7/15/2026",
    "currentReasonLeaving": "I'm moving for work.",
    "employer": "Pfizer",
    "employerAddress": "21823 30th Dr SE Bothell Wa 98021",
    "supervisorName": "Bianca Ramdath",
    "supervisorPhone": "(212) 557-9545",
    "jobTitle": "Summer 2026 Pfizer Research and Development Internship",
    "monthlyIncome": "$4,640.00",
    "annualIncome": "$55,680.00",
    "employmentStart": "5/26/2026",
    "ref1Name": "Anthony Ficaro",
    "ref1Relationship": "Colleague",
    "ref1Phone": "(630) 550-9325",
    "ref2Name": "Sydney Baker",
    "ref2Relationship": "Colleague",
    "ref2Phone": "(850) 206-9717",
    "occupancyCount": "5",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Ryan Gribble",
    "dateSigned": "4/16/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    ),
    (
      'AXIS-VRH8COLT',
      $axis_app_json$
{
  "id": "AXIS-VRH8COLT",
  "name": "Wesley Taylor",
  "property": "5259 Brooklyn Ave NE - 9 rooms",
  "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
  "managerUserId": "__AXIS_MANAGER_USER_ID__",
  "stage": "Submitted",
  "bucket": "pending",
  "email": "wbtaylor002@gmail.com",
  "detail": "Imported from spreadsheet - signed 4/15/2026",
  "application": {
    "applyingAsGroup": "yes",
    "groupRole": "joining",
    "groupId": "AXISGRP-P45NRJL764WE",
    "groupSize": "",
    "propertyId": "mgr-seed-5259-brooklyn-ave-ne",
    "roomChoice1": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-5",
    "roomChoice2": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-4",
    "roomChoice3": "mgr-seed-5259-brooklyn-ave-ne::seed-5259-brooklyn-room-6",
    "leaseTerm": "3-Month",
    "leaseStart": "5/21/2026",
    "leaseEnd": "8/15/2026",
    "fullLegalName": "Wesley Taylor",
    "dateOfBirth": "2/4/2005",
    "ssn": "655-20-2401",
    "driversLicense": "47038418",
    "phone": "(704) 307-5286",
    "email": "wbtaylor002@gmail.com",
    "currentStreet": "809 East Franklin Street",
    "currentCity": "Chapel Hill",
    "currentState": "NC",
    "currentZip": "27514",
    "currentLandlordName": "",
    "currentLandlordPhone": "",
    "currentMoveIn": "8/17/2025",
    "currentMoveOut": "5/11/2026",
    "currentReasonLeaving": "Internship",
    "employer": "Pfizer",
    "employerAddress": "21823 30th Dr SE Bothell WA 98021 United States",
    "supervisorName": "",
    "supervisorPhone": "",
    "jobTitle": "",
    "monthlyIncome": "",
    "annualIncome": "",
    "employmentStart": "",
    "ref1Name": "Mihir Upadhye",
    "ref1Relationship": "Prinicpal Investigator",
    "ref1Phone": "(805) 443-1675",
    "ref2Name": "Steven Mantekas",
    "ref2Relationship": "High School Boss",
    "ref2Phone": "(704) 560-5757",
    "occupancyCount": "1",
    "evictionHistory": "no",
    "bankruptcyHistory": "no",
    "criminalHistory": "no",
    "consentCredit": true,
    "consentTruth": true,
    "digitalSignature": "Wesley Taylor",
    "dateSigned": "4/15/2026",
    "applicationFeeAcknowledged": true
  }
}
      $axis_app_json$::jsonb
    )
)
insert into public.manager_application_records (
  id,
  manager_user_id,
  resident_email,
  property_id,
  assigned_property_id,
  row_data,
  updated_at
)
select
  seed.id,
  manager.id,
  lower(nullif(seed.row_data->>'email', '')),
  nullif(coalesce(seed.row_data->>'propertyId', seed.row_data #>> '{application,propertyId}'), ''),
  nullif(seed.row_data->>'assignedPropertyId', ''),
  jsonb_set(seed.row_data, '{managerUserId}', to_jsonb(manager.id::text), true),
  now()
from seed
cross join manager
on conflict (id) do update
set
  manager_user_id = excluded.manager_user_id,
  resident_email = excluded.resident_email,
  property_id = excluded.property_id,
  assigned_property_id = coalesce(manager_application_records.assigned_property_id, excluded.assigned_property_id),
  row_data = excluded.row_data
    || jsonb_strip_nulls(
      jsonb_build_object(
        'bucket', manager_application_records.row_data->'bucket',
        'stage', manager_application_records.row_data->'stage',
        'assignedPropertyId', manager_application_records.row_data->'assignedPropertyId',
        'assignedRoomChoice', manager_application_records.row_data->'assignedRoomChoice',
        'signedMonthlyRent', manager_application_records.row_data->'signedMonthlyRent'
      )
    ),
  updated_at = now();
