import type { RentalWizardFormState } from "./types";

export function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

export function createInitialRentalWizardState(): RentalWizardFormState {
  return {
    applicantRole: "signer",
    applyingAsGroup: null,
    groupRole: null,
    groupSize: "",
    groupId: "",
    groupLeaderAppId: "",
    hasCosigner: null,
    propertyId: "",
    roomChoice1: "",
    roomChoice2: "",
    roomChoice3: "",
    bundleId: "",
    rentalType: "standard",
    shortTermCheckInTime: "",
    shortTermCheckOutTime: "",
    shortTermRulesAck: false,
    leaseTerm: "",
    leaseStart: "",
    leaseEnd: "",
    managerRentOverride: "",
    managerUtilitiesOverride: "",
    managerSecurityDepositOverride: "",
    managerMoveInFeeOverride: "",
    managerOtherCostLabel: "",
    managerOtherCostAmount: "",
    fullLegalName: "",
    dateOfBirth: "",
    ssn: "",
    driversLicense: "",
    idPhotoFront: null,
    idPhotoBack: null,
    phone: "",
    email: "",
    smsConsent: false,
    currentStreet: "",
    currentCity: "",
    currentState: "",
    currentZip: "",
    currentLandlordName: "",
    currentLandlordPhone: "",
    currentMoveIn: "",
    currentMoveOut: "",
    currentReasonLeaving: "",
    noPreviousAddress: false,
    prevStreet: "",
    prevCity: "",
    prevState: "",
    prevZip: "",
    prevLandlordName: "",
    prevLandlordPhone: "",
    prevMoveIn: "",
    prevMoveOut: "",
    prevReasonLeaving: "",
    notEmployed: false,
    employer: "",
    employerAddress: "",
    supervisorName: "",
    supervisorPhone: "",
    jobTitle: "",
    monthlyIncome: "",
    annualIncome: "",
    employmentStart: "",
    otherIncome: "",
    incomeProofPhotos: [],
    ref1Name: "",
    ref1Relationship: "",
    ref1Phone: "",
    ref2Name: "",
    ref2Relationship: "",
    ref2Phone: "",
    occupancyCount: "",
    pets: "",
    evictionHistory: null,
    evictionDetails: "",
    bankruptcyHistory: null,
    bankruptcyDetails: "",
    criminalHistory: null,
    criminalDetails: "",
    consentCredit: false,
    consentTruth: false,
    digitalSignature: "",
    dateSigned: todayISO(),
    applicationFeeAcknowledged: false,
    applicationFeePayChannel: "ach",
    applicationFeeZelleSentConfirmed: false,
    applicationFeeWaiverCode: "",
    applicationFeeWaived: false,
    customFieldAnswers: [],
  };
}
